# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build IPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Git Clone Action
      # You may pin to the exact commit or the version.
      # uses: sudosubin/git-clone-action@8a93ce24d47782e30077508cccacf8a05a891bae
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        # Repository owner and name. Ex: sudosubin/git-clone-action
        repository: mpvkit/MPVKit # optional, default is ${{ github.repository }}
        # Git host platform. Ex: github, gitlab, bitbucket, gitee, or else (git.suckless.org, ...)
        #platform: # optional, default is github
        # Git branch or tag to checkout.
        ref: main # optional
        # Relative path from current directory, where to clone.
        path: ../../MPVKit # optional
    - name: Open Xcode project
      run: |
        open Rivulet.xcodeproj

    - name: Build project 
      run: xcodebuild -scheme Rivulet -destination 'generic/platform=tvOS' build
