# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build IPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
#    - name: Install MPVKit
#      uses: Cyberbeni/install-swift-tool@v3
#      with:
#        url: https://github.com/mpvkit/MPVKit
        # Version from Package.resolved is used if no commit/branch/version is provided.
#        commit: '613c0ccc3acf70e136aaff880a9b5fe8fdfaf5b8' # optional, commit hash
#        branch: main # optional, branch or tag, overridden by commit/version
#        version: '*' # optional, overridden by commit, format: https://devhints.io/semver
        #package-resolved-path: 'Package.resolved' # optional, default: 'Package.resolved', Package.resolved file path to use for resolving the version if no commit/branch/version is specified
#        use-cache: false # optinal, default: true
    - name: Open Xcode project
      run: |
        open Rivulet.xcodeproj

    - name: Build project 
      run: xcodebuild -scheme Rivulet -destination 'generic/platform=tvOS' build
